apiVersion: deskription.io/v1alpha1
kind: Resource
metadata:
  name: tekton-core-v1-pipelinerun
spec:
  selector:
    apiGroup: tekton.dev
    apiVersion: v1
    kind: PipelineRun
  type: CICD
---
apiVersion: deskription.io/v1alpha1
kind: ResourceTable
metadata:
  name: tekton-core-v1-pipelinerun
spec:
  selector:
    apiGroup: tekton.dev
    apiVersion: v1
    kind: PipelineRun
  columns:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: Created
      type: DateTime
      path: metadata.creationTimestamp
---
apiVersion: deskription.io/v1alpha1
kind: ResourceDetails
metadata:
  name: tekton-core-v1-pipelinerun
spec:
  selector:
    apiGroup: tekton.dev
    apiVersion: v1
    kind: PipelineRun
  fields:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: Labels
    - name: Namespace
      path: metadata.labels
    - name: Annotations
      path: metadata.annotations
