apiVersion: deskription.io/v1alpha1
kind: Resource
metadata:
  name: openshift-image-v1-imagestream
spec:
  selector:
    apiGroup: image.openshift.io
    apiVersion: v1
    kind: ImageStream
  type: CICD
---
apiVersion: deskription.io/v1alpha1
kind: ResourceTable
metadata:
  name: openshift-image-v1-imagestream
spec:
  selector:
    apiGroup: image.openshift.io
    apiVersion: v1
    kind: ImageStream
  columns:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: Created
      type: DateTime
      path: metadata.creationTimestamp
---
apiVersion: deskription.io/v1alpha1
kind: ResourceDetails
metadata:
  name: openshift-image-v1-imagestream
spec:
  selector:
    apiGroup: image.openshift.io
    apiVersion: v1
    kind: ImageStream
  fields:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: Labels
    - name: Namespace
      path: metadata.labels
    - name: Annotations
      path: metadata.annotations
