apiVersion: deskription.io/v1alpha1
kind: Resource
metadata:
  name: knative-serving-v1-route
spec:
  selector:
    apiGroup: serving.knative.dev
    apiVersion: v1
    kind: Route
  type: Workload
---
apiVersion: deskription.io/v1alpha1
kind: ResourceTable
metadata:
  name: knative-serving-v1-route
spec:
  selector:
    apiGroup: serving.knative.dev
    apiVersion: v1
    kind: Route
  columns:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: URL
    - name: Traffic
    - name: Created
      type: DateTime
      path: metadata.creationTimestamp
---
apiVersion: deskription.io/v1alpha1
kind: ResourceDetails
metadata:
  name: knative-serving-v1-route
spec:
  selector:
    apiGroup: serving.knative.dev
    apiVersion: v1
    kind: Route
  fields:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: Labels
    - name: Namespace
      path: metadata.labels
    - name: Annotations
      path: metadata.annotations
