apiVersion: deskription.io/v1alpha1
kind: Resource
metadata:
  name: kubernetes-policy-v1-poddisruptionbudget
spec:
  selector:
    apiGroup: policy
    apiVersion: v1
    kind: PodDisruptionBudget
  type: Workload
---
apiVersion: deskription.io/v1alpha1
kind: ResourceTable
metadata:
  name: kubernetes-policy-v1-poddisruptionbudget
spec:
  selector:
    apiGroup: policy
    apiVersion: v1
    kind: PodDisruptionBudget
  columns:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: Created
      type: DateTime
      path: metadata.creationTimestamp
---
apiVersion: deskription.io/v1alpha1
kind: ResourceDetails
metadata:
  name: kubernetes-policy-v1-poddisruptionbudget
spec:
  selector:
    apiGroup: policy
    apiVersion: v1
    kind: PodDisruptionBudget
  fields:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: Labels
    - name: Namespace
      path: metadata.labels
    - name: Annotations
      path: metadata.annotations
