apiVersion: deskription.io/v1alpha1
kind: Resource
metadata:
  name: kubernetes-core-v1-configmap
spec:
  selector:
    apiGroup: core
    apiVersion: v1
    kind: ConfigMap
  type: Data
---
apiVersion: deskription.io/v1alpha1
kind: ResourceTable
metadata:
  name: kubernetes-core-v1-configmap
spec:
  selector:
    apiGroup: core
    apiVersion: v1
    kind: ConfigMap
  columns:
    - name: Name
    - name: Type
    - name: Size
    - name: Created
      type: DateTime
      path: metadata.creationTimestamp
---
apiVersion: deskription.io/v1alpha1
kind: ResourceDetails
metadata:
  name: kubernetes-core-v1-configmap
spec:
  selector:
    apiGroup: core
    apiVersion: v1
    kind: ConfigMap
  fields:
    - name: Name
    - name: Namespace
    - name: Type
    - name: Labels
    - name: Annotations
    - name: Data
    - name: Binary data
