apiVersion: deskription.io/v1alpha1
kind: Resource
metadata:
  name: shipwright-core-v1alpha1-build
spec:
  selector:
    apiGroup: shipwright.io
    apiVersion: v1alpha1
    kind: Build
  type: CICD
---
apiVersion: deskription.io/v1alpha1
kind: ResourceTable
metadata:
  name: shipwright-core-v1alpha1-build
spec:
  selector:
    apiGroup: shipwright.io
    apiVersion: v1alpha1
    kind: Build
  columns:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: Output
    - name: Created
      type: DateTime
      path: metadata.creationTimestamp
---
apiVersion: deskription.io/v1alpha1
kind: ResourceDetails
metadata:
  name: shipwright-core-v1alpha1-build
spec:
  selector:
    apiGroup: shipwright.io
    apiVersion: v1alpha1
    kind: Build
  fields:
    - name: Namespace
      path: metadata.namespace
    - name: Name
      path: metadata.name
    - name: Labels
    - name: Namespace
      path: metadata.labels
    - name: Annotations
      path: metadata.annotations
    - name: Output
